### ISSUE TITLE
Set up GH OAuth Backend for Admin Dashboard

### ISSUE THREAD

**Issue by harshkhandeparkar** [metakgp/iqps-go#61]
### References
- https://github.com/kossiitkgp/KWoC-Backend?tab=readme-ov-file#github-oauth
- https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#web-application-flow

### Endpoints
- [ ] An endpoint that takes the `code` sent by frontend and sends back a JWT

### Middleware
- [ ] A middleware that parses JWTs in authenticated endpoints, and returns an error if unauthenticated.

**Comment by Bikram-ghuku** [comment]
Can I work on this?

**Comment by harshkhandeparkar** [comment]
> Can I work on this?
> 

Go ahead!
