### ISSUE TITLE
Set up Admin Dashboard Page

### ISSUE THREAD

**Issue by harshkhandeparkar** [metakgp/iqps-go#63]
### Features
- Cards/table for listing currently unapproved papers and their details
- Editable fields for the papers
- Either a paper modal or a PDF link that opens in a separate tab

**Comment by Majestic9169** [comment]
I would like to work on making this Admin Dashboard page very much, however I have only basic html/js experience.

Will I have to use the Solid frmework for this to work with the rest of the project? I have no experience with frameworks, so I will have to learn Solid if that is the case.

**Comment by harshkhandeparkar** [comment]
> I would like to work on making this Admin Dashboard page very much, however I have only basic html/js experience.

Great!

> Will I have to use the Solid frmework for this to work with the rest of the project? I have no experience with frameworks, so I will have to learn Solid if that is the case.

Yes, you will have to learn and use Solid. It's a good learning opportunity.

**Comment by Bikram-ghuku** [comment]
Can I work on this ?

**Comment by harshkhandeparkar** [comment]
@Bikram-ghuku please work on one issue at a time and let others work on the other issues :) Tegan's already working on this one.

**Comment by chirag-ghosh** [comment]
Sure. please go ahead

**Comment by proffapt** [comment]
@Majestic9169 updates?

**Comment by Majestic9169** [comment]
> @Majestic9169 updates?

No updates, was working on other things

Aaj se start krta hu

**Comment by Majestic9169** [comment]
> @Majestic9169 updates?

Frontend is at a good level for this to be useable. It can still developed further once backend starts

I haven't started learning go or backend yet because I was working on something else, I'll get started within the week and let you knoe
