### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by Denny-B-Justin** [metakgp/iqps-go#73]
**Describe the bug**
Not able to upload files.
![Screenshot 2024-06-29 111358](https://github.com/metakgp/iqps-go/assets/82396466/11d27d81-96c5-432d-9f99-3bc1d0dcb404)

![image](https://github.com/metakgp/iqps-go/assets/82396466/48789f28-38da-456e-825e-f6665dcbb1df)

**Comment by harshkhandeparkar** [comment]
@Denny-B-Justin can you tell the course code/name of the files you tried to upload?

**Comment by harshkhandeparkar** [comment]
@Denny-B-Justin the issue should be resolved now. Please confirm whether you are able to upload now. Thanks for the report!
