### ISSUE TITLE
Endpoint to update paper details

### ISSUE THREAD

**Issue by rajivharlalka** [metakgp/iqps-go#82]
- [x] Endpoint to approve papers: `/approve` and edit details.
- [ ] Endpoint to only edit details or disapprove/edit any details: `/edit`.
- [ ] Check for duplicates before approving any paper. At least throw an error so the replacement can be handled by a separate endpoint or some other means.

**Comment by proffapt** [comment]
@rajivharlalka or @harshkhandeparkar please update the state of this project to be reflected on the kanban.

**Comment by harshkhandeparkar** [comment]
Merging the first two endpoints into a single `/edit` endpoint that allows to change the approve status as well.
